-- Intentionally left blank.
--
-- This migration previously reset a hard-coded administrator password.
-- Password rotation must happen through the authentication provider and must
-- never be stored in repository history.
