-- Intentionally left blank.
--
-- This migration previously created an administrator with hard-coded credentials.
-- Bootstrap administrators outside version control using the documented procedure
-- in docs/admin-access.md. Never seed authentication passwords from migrations.
